# Generated by Django 5.0.6 on 2025-09-11 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=255)),
                ("duracion_anios", models.PositiveIntegerField()),
                ("activa", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[("M", "Mañana"), ("T", "Tarde"), ("V", "Vespertino")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("año", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("año", models.PositiveIntegerField()),
                (
                    "ciclo",
                    models.CharField(
                        choices=[
                            ("1C", "1º Cuatr."),
                            ("2C", "2º Cuatr."),
                            ("AN", "Anual"),
                        ],
                        default="1C",
                        max_length=2,
                        verbose_name="Ciclo Lectivo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Lunes"),
                            (2, "Martes"),
                            (3, "Miércoles"),
                            (4, "Jueves"),
                            (5, "Viernes"),
                            (6, "Sábado"),
                        ]
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                (
                    "comision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="academics.comision",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comision",
            name="materia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comisiones",
                to="academics.materia",
            ),
        ),
        migrations.CreateModel(
            name="Correlatividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requiere_aprobada", models.BooleanField(default=False)),
                ("requiere_regular", models.BooleanField(default=False)),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correlativas",
                        to="academics.materia",
                    ),
                ),
                (
                    "materia_correlativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="es_correlativa_de",
                        to="academics.materia",
                    ),
                ),
            ],
            options={
                "unique_together": {("materia", "materia_correlativa")},
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("año_implementacion", models.PositiveIntegerField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planes",
                        to="academics.carrera",
                    ),
                ),
            ],
            options={
                "unique_together": {("carrera", "version")},
            },
        ),
    ]
