# Generated by Django 5.0.6 on 2025-09-11 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ciclo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nombre", models.CharField(max_length=50)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Ciclo lectivo",
                "verbose_name_plural": "Ciclos lectivos",
                "ordering": ["orden", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="materia",
            options={"verbose_name": "Materia", "verbose_name_plural": "Materias"},
        ),
        migrations.AddField(
            model_name="materia",
            name="codigo",
            field=models.CharField(
                default="TEMP", max_length=10, verbose_name="Código"
            ),
        ),
        migrations.AddField(
            model_name="materia",
            name="cuatrimestre",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "1º Cuatrimestre"), (2, "2º Cuatrimestre")],
                null=True,
                verbose_name="Cuatrimestre",
            ),
        ),
        migrations.AddField(
            model_name="materia",
            name="horas_semanales",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Horas Semanales"
            ),
        ),
        migrations.AddField(
            model_name="materia",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materias",
                to="academics.plan",
            ),
        ),
        migrations.AddField(
            model_name="materia",
            name="puntos_credito",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Puntos de Crédito"
            ),
        ),
        migrations.AlterField(
            model_name="materia",
            name="año",
            field=models.PositiveIntegerField(verbose_name="Año"),
        ),
        migrations.AlterField(
            model_name="materia",
            name="nombre",
            field=models.CharField(max_length=200, verbose_name="Nombre"),
        ),
        migrations.AlterUniqueTogether(
            name="materia",
            unique_together={("plan", "codigo")},
        ),
        migrations.AlterField(
            model_name="materia",
            name="ciclo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="materias",
                to="academics.ciclo",
            ),
        ),
    ]
