# Generated by Django 5.0.6 on 2025-09-11 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_ciclo_alter_materia_options_materia_codigo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materia",
            name="plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materias",
                to="academics.plan",
            ),
        ),
    ]
