# Generated by Django 5.0.6 on 2025-09-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_alter_materia_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="comision",
            name="cupo_maximo",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Solo alertas; no bloquea ni abre comisiones.",
                null=True,
            ),
        ),
    ]
