# Generated by Django 5.0.6 on 2025-09-12 20:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0004_comision_cupo_maximo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preinscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cuil",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CUIL/CUIT con formato 00-00000000-0",
                                regex="^\\d{2}-\\d{8}-\\d{1}$",
                            )
                        ],
                        verbose_name="CUIL/CUIT",
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        max_length=8,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="DNI debe tener 8 dígitos", regex="^\\d{8}$"
                            )
                        ],
                        verbose_name="DNI",
                    ),
                ),
                ("apellido", models.CharField(max_length=80)),
                ("nombres", models.CharField(max_length=120)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "estado_civil",
                    models.CharField(
                        choices=[
                            ("SOLTERO", "Soltero/a"),
                            ("CASADO", "Casado/a"),
                            ("DIVORCIADO", "Divorciado/a"),
                            ("VIUDO", "Viudo/a"),
                            ("OTRO", "Otro"),
                        ],
                        default="SOLTERO",
                        max_length=15,
                    ),
                ),
                ("localidad_nac", models.CharField(max_length=80)),
                ("provincia_nac", models.CharField(max_length=80)),
                ("pais_nac", models.CharField(max_length=80)),
                ("nacionalidad", models.CharField(max_length=80)),
                ("domicilio", models.CharField(max_length=200)),
                ("tel_fijo", models.CharField(blank=True, max_length=30)),
                ("tel_movil", models.CharField(blank=True, max_length=30)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("trabaja", models.BooleanField(default=False)),
                ("empleador", models.CharField(blank=True, max_length=120)),
                ("horario_trabajo", models.CharField(blank=True, max_length=120)),
                ("domicilio_trabajo", models.CharField(blank=True, max_length=200)),
                ("sec_titulo", models.CharField(blank=True, max_length=160)),
                ("sec_establecimiento", models.CharField(blank=True, max_length=160)),
                ("sec_fecha_egreso", models.DateField(blank=True, null=True)),
                ("sec_localidad", models.CharField(blank=True, max_length=120)),
                ("sec_provincia", models.CharField(blank=True, max_length=120)),
                ("sec_pais", models.CharField(blank=True, max_length=120)),
                ("sup1_titulo", models.CharField(blank=True, max_length=160)),
                ("sup1_establecimiento", models.CharField(blank=True, max_length=160)),
                ("sup1_fecha_egreso", models.DateField(blank=True, null=True)),
                ("sup1_localidad", models.CharField(blank=True, max_length=120)),
                ("sup1_provincia", models.CharField(blank=True, max_length=120)),
                ("sup1_pais", models.CharField(blank=True, max_length=120)),
                ("sup2_titulo", models.CharField(blank=True, max_length=160)),
                ("sup2_establecimiento", models.CharField(blank=True, max_length=160)),
                ("sup2_fecha_egreso", models.DateField(blank=True, null=True)),
                ("sup2_localidad", models.CharField(blank=True, max_length=120)),
                ("sup2_provincia", models.CharField(blank=True, max_length=120)),
                ("sup2_pais", models.CharField(blank=True, max_length=120)),
                (
                    "foto_4x4",
                    models.ImageField(
                        blank=True, null=True, upload_to="preinsc/fotos/"
                    ),
                ),
                ("doc_fotocopia_titulo_legalizada", models.BooleanField(default=False)),
                (
                    "doc_fotocopia_analitico_legalizada",
                    models.BooleanField(default=False),
                ),
                ("doc_fotos_4x4", models.BooleanField(default=False)),
                ("doc_titulo_secundario", models.BooleanField(default=False)),
                (
                    "doc_titulo_terciario_universitario",
                    models.BooleanField(default=False),
                ),
                ("doc_cert_alumno_regular", models.BooleanField(default=False)),
                ("doc_cert_titulo_en_tramite", models.BooleanField(default=False)),
                ("doc_cert_buena_salud", models.BooleanField(default=False)),
                ("doc_folios", models.BooleanField(default=False)),
                ("doc_adeuda_materias", models.BooleanField(default=False)),
                ("adeuda_materias_detalle", models.TextField(blank=True)),
                (
                    "adeuda_materias_escuela",
                    models.CharField(blank=True, max_length=160),
                ),
                ("doc_incumbencias", models.BooleanField(default=False)),
                ("doc_declaracion_jurada", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academics.carrera",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
