# Generated by Django 5.0.6 on 2025-09-14 02:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preinscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="preinscripcion",
            options={"ordering": ["-creado"]},
        ),
        migrations.AddField(
            model_name="preinscripcion",
            name="anio",
            field=models.PositiveIntegerField(db_index=True, default=2025),
        ),
        migrations.AddField(
            model_name="preinscripcion",
            name="comprobante_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="preinscripciones/"
            ),
        ),
        migrations.AddField(
            model_name="preinscripcion",
            name="creado",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="preinscripcion",
            name="numero",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=32,
                null=True,
                unique=True,
                verbose_name="Número",
            ),
        ),
    ]
