# Generated by Django 5.0.6 on 2025-09-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preinscriptions", "0005_preinscripcion_comprobante_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preinscripcionsequence",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
