# Generated by Django 5.0.6 on 2025-09-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preinscriptions", "0006_alter_preinscripcionsequence_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="preinscripcion",
            name="estado",
            field=models.CharField(
                choices=[("NUEVA", "Nueva"), ("CONFIRMADA", "Confirmada")],
                default="NUEVA",
                max_length=15,
            ),
        ),
    ]
