# Generated by Django 5.0.6 on 2025-09-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preinscriptions", "0008_portal_user_and_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portalnotification",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
