# Generated by Django 5.0.6 on 2025-09-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dni",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
