# Generated by Django 5.0.6 on 2025-09-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_dni"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="foto_4x4",
            field=models.ImageField(
                blank=True,
                help_text="Foto tipo carnet 4x4 del estudiante",
                null=True,
                upload_to="users/foto4x4/",
            ),
        ),
    ]
