# Generated by Django 5.0.6 on 2025-09-11 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_alter_materia_plan"),
        ("inscriptions", "0004_rename_created_at_to_fecha_inscripcion_examen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del Período"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("CURSADA", "Cursada"), ("EXAMEN", "Examen")],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(verbose_name="Fecha de Inicio")),
                ("fecha_fin", models.DateTimeField(verbose_name="Fecha de Fin")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Período",
                "verbose_name_plural": "Períodos",
            },
        ),
        migrations.AlterModelOptions(
            name="inscripcioncursada",
            options={
                "verbose_name": "Inscripción a Cursada",
                "verbose_name_plural": "Inscripciones a Cursada",
            },
        ),
        migrations.AlterModelOptions(
            name="inscripcionexamen",
            options={
                "verbose_name": "Inscripción a Examen",
                "verbose_name_plural": "Inscripciones a Examen",
            },
        ),
        migrations.AddField(
            model_name="inscripcionexamen",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("CONFIRMADA", "Confirmada"),
                    ("PRESENTE", "Presente"),
                    ("AUSENTE", "Ausente"),
                    ("APROBADO", "Aprobado"),
                    ("DESAPROBADO", "Desaprobado"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inscripcionexamen",
            name="fecha_examen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inscripcionexamen",
            name="intento",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="inscripcionexamen",
            name="nota",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="inscripcioncursada",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("CONFIRMADA", "Confirmada"),
                    ("REGULAR", "Regular"),
                    ("LIBRE", "Libre"),
                    ("BAJA", "Baja"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inscripcioncursada",
            unique_together={("estudiante", "comision")},
        ),
        migrations.AlterUniqueTogether(
            name="inscripcionexamen",
            unique_together={("estudiante", "materia", "intento")},
        ),
        migrations.DeleteModel(
            name="Regularidad",
        ),
    ]
