# Generated by Django 5.0.6 on 2025-09-12 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_comision_cupo_maximo"),
        ("inscriptions", "0005_periodo_alter_inscripcioncursada_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inscripcioncursada",
            name="motivo_condicion",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="inscripcioncursada",
            name="tipo",
            field=models.CharField(
                choices=[("REGULAR", "Regular"), ("OYENTE", "Oyente")],
                default="REGULAR",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="inscripcioncursada",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("CONFIRMADA", "Confirmada"),
                    ("CONDICIONAL", "Condicional por conflicto"),
                    ("REGULAR", "Regular"),
                    ("LIBRE", "Libre"),
                    ("BAJA", "Baja"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("CONFLICTO_HORARIO", "Conflicto de horario")],
                        max_length=40,
                    ),
                ),
                ("detalle", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("ABIERTA", "Abierta"), ("RESUELTA", "Resuelta")],
                        default="ABIERTA",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comision_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="academics.comision",
                    ),
                ),
                (
                    "comision_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="academics.comision",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InscripcionCarrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_alta", models.DateTimeField(auto_now_add=True)),
                (
                    "estado_legajo",
                    models.CharField(
                        choices=[
                            ("COMPLETO", "Completo"),
                            ("INCOMPLETO", "Incompleto"),
                        ],
                        default="INCOMPLETO",
                        max_length=12,
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("CONDICIONADO", "Condicionado"),
                        ],
                        default="CONDICIONADO",
                        max_length=13,
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.carrera",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        limit_choices_to={"rol": "ESTUDIANTE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones_carrera",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("estudiante", "carrera")},
            },
        ),
        migrations.CreateModel(
            name="LegajoItemTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("obligatorio", models.BooleanField(default=True)),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legajo_items_def",
                        to="academics.carrera",
                    ),
                ),
            ],
            options={
                "unique_together": {("carrera", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="SolicitudExComision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "comision_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.comision",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        limit_choices_to={"rol": "ESTUDIANTE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.materia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegajoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completo", models.BooleanField(default=False)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "insc_carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="inscriptions.inscripcioncarrera",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inscriptions.legajoitemtipo",
                    ),
                ),
            ],
            options={
                "unique_together": {("insc_carrera", "item")},
            },
        ),
    ]
